Algoritmo "consumo"

Var

   distanciaTotal, combustivelGasto, consumo : real

Inicio

      ESCREVA ("Insira a distancia total: ")
      LEIA (distanciaTotal)
      ESCREVA ("Insira o total de combustivel gasto: ")
      LEIA (combustivelGasto)
      
      consumo <- distanciaTotal/ combustivelGasto
      ESCREVAL ("")
      ESCREVA ("O consumo medio de combustivel é de ", consumo:8:3)

Fimalgoritmo