Algoritmo "crescente"

Var

   x, y : inteiro

Inicio

   ESCREVAL ("Digite dois numeros: ")
   LEIA (x)
   LEIA (y)

   ENQUANTO x <> y FACA
            SE X > Y ENTAO
               ESCREVAl ("DECRESCENTE!")
            SENAO
               ESCREVAl ("CRESCENTE!!")
            FIMSE
            ESCREVAL ("Digite outros dois numeros: ")
            LEIA (x)
            LEIA (y)
   FIMENQUANTO

Fimalgoritmo